version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db_raizes"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge