version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db_raizes"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    networks:
      - docker-network
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    volumes:
      - "./minio/data:/data"
      - "./minio/minio:/minio"
      - "./minio/config:/root/.minio"
    environment:
      TZ: America/Sao_Paulo
      LANG: pt_BR.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ACCESS_KEY: "victor"
      MINIO_SECRET_KEY: "12345678"
    command: server /data  --console-address ":9001"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - "9000:9000" # file upload&preview port
      - "9001:9001"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge