spring.application.name=teste
spring.datasource.url=jdbc:postgresql://localhost:5432/db_raizes?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=3
# 30 minutos em milissegundos
spring.datasource.hikari.max-lifetime=1800000
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql=true
spring.jpa.properties.org.hibernate.envers.revision_field_name=cd_auditoria
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=tp_movimento
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true
flyway.url=jdbc:postgresql://localhost:5432/db_raizes?currentSchema=public
flyway.user=postgres
flyway.password=postgres
flyway.locations=classpath:db/migration