package com.devictoralmeida.teste.enums;

public enum GrauInstrucao {
  ALFABETIZADO,
  NAO_ALFABETIZADO,
  PRIMEIRO_GRAU_COMPLETO,
  PRIMEIRO_GRAU_INCOMPLETO,
  SEGUNDO_GRAU_COMPLETO,
  SEGUNDO_GRAU_INCOMPLETO,
  SUPERIOR_COMPLETO,
  SUPERIOR_INCOMPLETO,
  POS_GRADUADO,
  POS_GRADUADO_INCOMPLETO
}
